### ISSUE TITLE
Nested unordered lists: nullpointerexception

### ISSUE THREAD

**Issue by cweiske** [sangupta/nutz#3]
The following markup produces a NullPointerException:
```
* Item 1
* Item 2
* Item 3
    * Item 3a
    * Item 3b
    * Item 3c
```

stack trace:
```
java.lang.NullPointerException
	at com.sangupta.nutz.Parser.parseList(Parser.java:448)
	at com.sangupta.nutz.Parser.parseLine(Parser.java:244)
	at com.sangupta.nutz.Parser.readLines(Parser.java:192)
	at com.sangupta.nutz.Parser.parse(Parser.java:137)
```

See https://jira.atlassian.com/browse/CONFSERVER-44227

**Comment by sangupta** [comment]
@cweiske Was travelling and thus could reply earlier. I have been able to reproduce both the issues and will get a fix in a few days. Thanks for reporting.

**Comment by cweiske** [comment]
Good that you could reproduce the issue.
